name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # 中国时间凌晨 2 点

env:
  GIT_AUTHOR: Ruikoto <30781137+Ruikoto@users.noreply.github.com>
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  nightly-build:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: GTNH-UCN/Translation-of-GTNH
          ref: main
          path: repo
          token: ${{ secrets.GH_TOKEN }}

      - name: Verify pack.py Exists
        run: ls -lah repo/.github/scripts/

      - name: Setup Datetime Related Envs
        shell: python
        run: |
          import os
          from datetime import datetime, timezone, timedelta
          local_date = datetime.now(timezone(timedelta(hours=8))).strftime("%Y-%m-%d")
          local_time = datetime.now(timezone(timedelta(hours=8))).strftime("%H:%M:%S")
          with open(os.environ['GITHUB_ENV'], 'a') as f:
              print(f'NB_LOCAL_DATE={local_date}', file=f)
              print(f'NB_LOCAL_TIME={local_time}', file=f)
              print(f'NB_TAG=0-nightly-build/{local_date}', file=f)

      - name: Ensure Temp & Assets Directories
        run: |
          mkdir -p repo/temp
          mkdir -p repo/assets

      - name: Run Packaging Script
        working-directory: repo
        run: python .github/scripts/pack.py

      - name: Zip Output
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repo/assets/nightly-${{ env.NB_LOCAL_DATE }}.7z repo/temp/*

      - name: Push tag
        working-directory: repo
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout --orphan temp
          git reset HEAD -- .
          git commit --allow-empty -m "Nightly Build ${{ env.NB_LOCAL_DATE }} ${{ env.NB_LOCAL_TIME }}"
          git tag ${{ env.NB_TAG }}
          git push --delete origin ${{ env.NB_TAG }} || true
          git push origin ${{ env.NB_TAG }}

      - name: Release Nightly Build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NB_TAG }}
          name: 每日构建 - ${{ env.NB_LOCAL_DATE }}
          body: |
            请阅读主页 ReadMe 以获知详细用法
            
            自动构建于 ${{ env.NB_LOCAL_DATE }} ${{ env.NB_LOCAL_TIME }}
          files: |
            repo/assets/nightly-${{ env.NB_LOCAL_DATE }}.7z